/* GLOBAL TYPES */
export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';

/* ROOM TYPES */
export const ROOM_CREATE = 'ROOM_CREATE';
export const ROOM_GET = 'ROOM_GET';

/* VIDEO TYPES */
export const VIDEO_ON_PLAYING = 'VIDEO_ON_PLAYING';